"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports._pStreetName = exports._postalCode = exports._streetNr = exports._streenName = exports._address = exports._favColors = exports._email = exports._name = void 0;
var monocle_ts_1 = require("monocle-ts");
exports._name = monocle_ts_1.Lens.fromProp()("name");
exports._email = monocle_ts_1.Lens.fromProp()("email");
exports._favColors = monocle_ts_1.Lens.fromProp()("favoriteColors");
exports._address = monocle_ts_1.Lens.fromProp()("address");
exports._streenName = monocle_ts_1.Lens.fromProp()("streetName");
exports._streetNr = monocle_ts_1.Lens.fromProp()("streetNr");
exports._postalCode = monocle_ts_1.Lens.fromProp()("postalCode");
exports._pStreetName = exports._address.compose(exports._streenName);
